project:
  type: website

website:
  title: "ImgLib2 and BigDataViewer projects"
  navbar:
    right:
      - text: "ImgLib2"
        href: "imglib2"
      - text: "BDV"
        href: "bdv"
      - text: Blog
        href: blog.qmd
      - text: Resources
        menu:
             - text: "ImgLib2 links"
               icon: "info-square"
               href: "resources/imglib2_links.qmd"
             - text: "BigDataViewer links"
               icon: "info-square"
               href: "resources/bigdataviewer_links.qmd"
             - text: "ImgLib2 github"
               icon: "github"
               href: "https://github.com/imglib"
             - text: "BigDataViewer github"
               icon: "github"
               href: "https://github.com/bigdataviewer"

      - text: Ecosystem
        href: ecosystem/index.qmd
      - text: Contributing Guidelines
        menu:
             - text: "Guidelines for ImgLib2"
               icon: "share"
               href: "contribute/guidelines_for_imglib2.qmd"
             - text: "Guidelines for BigDataViewer"
               icon: "share"
               href: "contribute/guidelines_for_bigdataviewer.qmd"
             - text: "Our Code-of-conduct"
               icon: "peace"
               href: "contribute/our_code_of_conduct.qmd"
      - text: ""
      - icon: mastodon
        href: https://fosstodon.org/@imglib2
  open-graph: true
  repo-url: https://github.com/imglib/imglib2-www
  site-url: https://imglib.github.io/imglib2-www
  # Sidebar configuration using Hybrid Navigation, as described at:
  # https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation
  # The intent is for the ImgLib2 section of the site to show all ImgLib2
  # articles in a dedicated sidebar, and similarly, for the BigDataViewer
  # section of the site to show all BigDataViewer articles in its sidebar.
  sidebar:
    - title: "BigDataViewer"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - bdv/index.qmd
        - auto: "bdv/*"
    - title: "ImgLib2"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - imglib2/index.qmd
        - auto: "imglib2/*"
    - title: "ImgLib1 (obsolete!)"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - imglib1/index.qmd
        - auto: "imglib1/*"
sidebar: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    code-overflow: wrap
    code-tools:
      source: repo

